services:
  metamcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metamcp-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=3000
      - MCP_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - metamcp-network
    # Resource limits to prevent memory leaks
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
          pids: 25
        reservations:
          memory: 1g
          cpus: '0.5'
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # Health check to auto-restart on memory issues
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Logging limits
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
      - metamcp-cache:/app/.cache

  postgres:
    image: postgres:16-alpine
    container_name: metamcp-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "9543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres:/docker-entrypoint-initdb.d
    networks:
      - metamcp-network
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.25'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: metamcp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - metamcp-network
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
        reservations:
          memory: 128m
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Process monitor service
  process-monitor:
    image: alpine:latest
    container_name: metamcp-process-monitor
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/scripts
    command: ["sh", "/scripts/metamcp-process-killer.sh"]
    networks:
      - metamcp-network
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: '0.1'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  metamcp-cache:
    driver: local

networks:
  metamcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16